# Generated by Django 4.2.5 on 2023-09-28 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pepapp1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Businesses',
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
